# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'agepyramid_reproductive' so R CMD check does not flag undocumented data.
#' agepyramid_reproductive: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 400 rows and 3 variables:
#' \describe{
#'   \item{id}{integer variable}
#'   \item{gender}{character variable}
#'   \item{age}{numeric variable}
#' }
#' @keywords datasets internal
"agepyramid_reproductive"

