# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'outlierdetection_temporal' so R CMD check does not flag undocumented data.
#' outlierdetection_temporal: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 200 rows and 6 variables:
#' \describe{
#'   \item{patient_id}{integer variable}
#'   \item{time_point}{character variable}
#'   \item{stable_measure}{numeric variable}
#'   \item{treatment_response}{numeric variable}
#'   \item{seasonal_measure}{numeric variable}
#'   \item{biomarker_decline}{numeric variable}
#' }
#' @keywords datasets internal
"outlierdetection_temporal"

