# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'outlierdetection_psychological' so R CMD check does not flag undocumented data.
#' outlierdetection_psychological: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 200 rows and 11 variables:
#' \describe{
#'   \item{patient_id}{integer variable}
#'   \item{anxiety_score}{numeric variable}
#'   \item{depression_score}{numeric variable}
#'   \item{stress_score}{numeric variable}
#'   \item{iq_score}{numeric variable}
#'   \item{reaction_time}{numeric variable}
#'   \item{memory_score}{numeric variable}
#'   \item{sleep_hours}{numeric variable}
#'   \item{exercise_minutes}{numeric variable}
#'   \item{screen_time_hours}{numeric variable}
#'   \item{quality_of_life}{numeric variable}
#' }
#' @keywords datasets internal
"outlierdetection_psychological"

