# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'outlierdetection_problematic' so R CMD check does not flag undocumented data.
#' outlierdetection_problematic: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 50 rows and 10 variables:
#' \describe{
#'   \item{patient_id}{integer variable}
#'   \item{all_na}{logical variable}
#'   \item{mostly_na}{numeric variable}
#'   \item{infinite_values}{numeric variable}
#'   \item{very_large}{numeric variable}
#'   \item{character_data}{character variable}
#'   \item{mixed_types}{character variable}
#'   \item{single_value}{numeric variable}
#'   \item{two_values}{numeric variable}
#'   \item{extreme_outliers}{numeric variable}
#' }
#' @keywords datasets internal
"outlierdetection_problematic"

