# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'outlierdetection_international' so R CMD check does not flag undocumented data.
#' outlierdetection_international: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 150 rows and 11 variables:
#' \describe{
#'   \item{patient_id}{integer variable}
#'   \item{weight_kg}{numeric variable}
#'   \item{height_cm}{numeric variable}
#'   \item{temperature_celsius}{numeric variable}
#'   \item{weight_lbs}{numeric variable}
#'   \item{height_inches}{numeric variable}
#'   \item{temperature_fahrenheit}{numeric variable}
#'   \item{glucose_mmol}{numeric variable}
#'   \item{glucose_mg_dl}{numeric variable}
#'   \item{dosage_mg}{numeric variable}
#'   \item{pain_scale}{numeric variable}
#' }
#' @keywords datasets internal
"outlierdetection_international"

