# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'tableone_test' so R CMD check does not flag undocumented data.
#' tableone_test: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 150 rows and 19 variables:
#' \describe{
#'   \item{PatientID}{character variable}
#'   \item{Age}{numeric variable}
#'   \item{Sex}{character variable}
#'   \item{TumorSize}{numeric variable}
#'   \item{TumorStage}{ordered/factor variable}
#'   \item{Grade}{ordered/factor variable}
#'   \item{LymphNodes}{character variable}
#'   \item{LVI}{character variable}
#'   \item{PNI}{character variable}
#'   \item{PreinvasiveComponent}{character variable}
#'   \item{TumorType}{character variable}
#'   \item{Hemoglobin}{numeric variable}
#'   \item{WBC}{numeric variable}
#'   \item{Ki67}{numeric variable}
#'   \item{CA199}{numeric variable}
#'   \item{Treatment}{character variable}
#'   \item{Response}{character variable}
#'   \item{FollowUpMonths}{numeric variable}
#'   \item{VitalStatus}{character variable}
#' }
#' @keywords datasets internal
"tableone_test"

