# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'multi_group_workflow' so R CMD check does not flag undocumented data.
#' multi_group_workflow: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 9 rows and 3 variables:
#' \describe{
#'   \item{workflow_from}{character variable}
#'   \item{workflow_to}{character variable}
#'   \item{group_category}{character variable}
#' }
#' @keywords datasets internal
"multi_group_workflow"

