# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'chisqposttest_test_data' so R CMD check does not flag undocumented data.
#' chisqposttest_test_data: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 300 rows and 14 variables:
#' \describe{
#'   \item{PatientID}{integer variable}
#'   \item{Treatment}{factor variable}
#'   \item{Response}{factor variable}
#'   \item{Sex}{factor variable}
#'   \item{TumorGrade}{factor variable}
#'   \item{TumorStage}{factor variable}
#'   \item{Institution}{factor variable}
#'   \item{QualityScore}{factor variable}
#'   \item{RandomVar1}{factor variable}
#'   \item{RandomVar2}{factor variable}
#'   \item{RareCategory}{factor variable}
#'   \item{BinaryOutcome}{factor variable}
#'   \item{AgeGroup}{factor variable}
#'   \item{BiomarkerStatus}{factor variable}
#' }
#' @keywords datasets internal
"chisqposttest_test_data"

