# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'outlierdetection_edge_cases' so R CMD check does not flag undocumented data.
#' outlierdetection_edge_cases: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 100 rows and 11 variables:
#' \describe{
#'   \item{patient_id}{integer variable}
#'   \item{identical_values}{numeric variable}
#'   \item{nearly_identical}{numeric variable}
#'   \item{small_variance}{numeric variable}
#'   \item{large_variance}{numeric variable}
#'   \item{extreme_values}{numeric variable}
#'   \item{missing_data}{numeric variable}
#'   \item{discrete_values}{numeric variable}
#'   \item{binary_like}{numeric variable}
#'   \item{skewed_data}{numeric variable}
#'   \item{bimodal_data}{numeric variable}
#' }
#' @keywords datasets internal
"outlierdetection_edge_cases"

