# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'ihc_test_data' so R CMD check does not flag undocumented data.
#' ihc_test_data: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 100 rows and 9 variables:
#' \describe{
#'   \item{SampleID}{character variable}
#'   \item{ER}{character variable}
#'   \item{PR}{character variable}
#'   \item{HER2}{character variable}
#'   \item{Ki67}{character variable}
#'   \item{p53}{character variable}
#'   \item{CD3}{character variable}
#'   \item{CD20}{character variable}
#'   \item{CD45}{character variable}
#' }
#' @keywords datasets internal
"ihc_test_data"

