# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'sarcoma_ihc_data' so R CMD check does not flag undocumented data.
#' sarcoma_ihc_data: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 300 rows and 18 variables:
#' \describe{
#'   \item{Patient_ID}{character variable}
#'   \item{Age}{numeric variable}
#'   \item{Gender}{factor variable}
#'   \item{Tumor_Type}{factor variable}
#'   \item{Tumor_Size_cm}{numeric variable}
#'   \item{Tumor_Grade}{factor variable}
#'   \item{Vimentin}{factor variable}
#'   \item{SMA}{factor variable}
#'   \item{Desmin}{factor variable}
#'   \item{S100}{factor variable}
#'   \item{CD34}{factor variable}
#'   \item{Cytokeratin}{factor variable}
#'   \item{EMA}{factor variable}
#'   \item{MDM2}{factor variable}
#'   \item{CDK4}{factor variable}
#'   \item{MyoD1}{factor variable}
#'   \item{Overall_Survival_Months}{numeric variable}
#'   \item{Death_Event}{integer variable}
#' }
#' @keywords datasets internal
"sarcoma_ihc_data"

