# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'outlierdetection_multivariate' so R CMD check does not flag undocumented data.
#' outlierdetection_multivariate: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 200 rows and 6 variables:
#' \describe{
#'   \item{patient_id}{integer variable}
#'   \item{biomarker_1}{numeric variable}
#'   \item{biomarker_2}{numeric variable}
#'   \item{biomarker_3}{numeric variable}
#'   \item{clinical_score}{numeric variable}
#'   \item{composite_index}{numeric variable}
#' }
#' @keywords datasets internal
"outlierdetection_multivariate"

