# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'outlierdetection_clinical' so R CMD check does not flag undocumented data.
#' outlierdetection_clinical: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 300 rows and 15 variables:
#' \describe{
#'   \item{patient_id}{integer variable}
#'   \item{hemoglobin}{numeric variable}
#'   \item{hematocrit}{numeric variable}
#'   \item{white_blood_cells}{numeric variable}
#'   \item{platelets}{numeric variable}
#'   \item{glucose}{numeric variable}
#'   \item{creatinine}{numeric variable}
#'   \item{bun}{numeric variable}
#'   \item{sodium}{numeric variable}
#'   \item{potassium}{numeric variable}
#'   \item{alt}{numeric variable}
#'   \item{ast}{numeric variable}
#'   \item{bilirubin}{numeric variable}
#'   \item{troponin}{numeric variable}
#'   \item{ck_mb}{numeric variable}
#' }
#' @keywords datasets internal
"outlierdetection_clinical"

