# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'ggflowchart_comprehensive_data' so R CMD check does not flag undocumented data.
#' ggflowchart_comprehensive_data: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 25 rows and 4 variables:
#' \describe{
#'   \item{workflow_type}{character variable}
#'   \item{from_var}{character variable}
#'   \item{to_var}{character variable}
#'   \item{group_var}{character variable}
#' }
#' @keywords datasets internal
"ggflowchart_comprehensive_data"

