# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'election_survey_data' so R CMD check does not flag undocumented data.
#' election_survey_data: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 300 rows and 11 variables:
#' \describe{
#'   \item{age_group}{factor variable}
#'   \item{gender}{factor variable}
#'   \item{education}{factor variable}
#'   \item{region}{factor variable}
#'   \item{party_support}{factor variable}
#'   \item{voting_likelihood}{integer variable}
#'   \item{top_issue}{factor variable}
#'   \item{pm_approval}{integer variable}
#'   \item{government_approval}{integer variable}
#'   \item{poll_date}{Date variable}
#'   \item{sample_weight}{numeric variable}
#' }
#' @keywords datasets internal
"election_survey_data"

