# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'raw_with_time' so R CMD check does not flag undocumented data.
#' raw_with_time: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 20 rows and 3 variables:
#' \describe{
#'   \item{PatientID}{character variable}
#'   \item{Time}{numeric variable}
#'   \item{Measurement}{numeric variable}
#' }
#' @keywords datasets internal
"raw_with_time"

