# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'outlierdetection_basic' so R CMD check does not flag undocumented data.
#' outlierdetection_basic: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 200 rows and 9 variables:
#' \describe{
#'   \item{patient_id}{integer variable}
#'   \item{age}{numeric variable}
#'   \item{weight}{numeric variable}
#'   \item{height}{numeric variable}
#'   \item{bmi}{numeric variable}
#'   \item{bp_systolic}{numeric variable}
#'   \item{bp_diastolic}{numeric variable}
#'   \item{lab_value}{numeric variable}
#'   \item{treatment_response}{numeric variable}
#' }
#' @keywords datasets internal
"outlierdetection_basic"

