# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'outlierdetection_large' so R CMD check does not flag undocumented data.
#' outlierdetection_large: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 2000 rows and 11 variables:
#' \describe{
#'   \item{patient_id}{integer variable}
#'   \item{variable_1}{numeric variable}
#'   \item{variable_2}{numeric variable}
#'   \item{variable_3}{numeric variable}
#'   \item{variable_4}{numeric variable}
#'   \item{variable_5}{numeric variable}
#'   \item{variable_6}{numeric variable}
#'   \item{variable_7}{numeric variable}
#'   \item{variable_8}{numeric variable}
#'   \item{variable_9}{numeric variable}
#'   \item{variable_10}{numeric variable}
#' }
#' @keywords datasets internal
"outlierdetection_large"

