# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'complex_alluvial_data' so R CMD check does not flag undocumented data.
#' complex_alluvial_data: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 500 rows and 8 variables:
#' \describe{
#'   \item{record_id}{integer variable}
#'   \item{level_1}{character variable}
#'   \item{level_2}{character variable}
#'   \item{level_3}{character variable}
#'   \item{level_4}{character variable}
#'   \item{revenue}{numeric variable}
#'   \item{customer_segment}{character variable}
#'   \item{time_quarter}{character variable}
#' }
#' @keywords datasets internal
"complex_alluvial_data"

