# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'treatmentResponse' so R CMD check does not flag undocumented data.
#' treatmentResponse: example dataset for the ClinicoPathDescriptives module
#'
#' Example dataset distributed with the ClinicoPathDescriptives jamovi module for demonstration and testing.
#'
#' @format A data frame with 250 rows and 2 variables:
#' \describe{
#'   \item{PatientID}{character variable}
#'   \item{ResponseValue}{numeric variable}
#' }
#' @keywords datasets internal
"treatmentResponse"

