
# This file is automatically generated, you probably don't want to edit this

vartreeOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "vartreeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            excl = TRUE,
            horizontal = FALSE,
            sline = TRUE,
            varnames = FALSE,
            pct = FALSE,
            mytitle = "Variable Tree",
            imagewidth = 10, ...) {

            super$initialize(
                package='ClinicoPathDescriptives',
                name='vartree',
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..excl <- jmvcore::OptionBool$new(
                "excl",
                excl,
                default=TRUE)
            private$..horizontal <- jmvcore::OptionBool$new(
                "horizontal",
                horizontal,
                default=FALSE)
            private$..sline <- jmvcore::OptionBool$new(
                "sline",
                sline,
                default=TRUE)
            private$..varnames <- jmvcore::OptionBool$new(
                "varnames",
                varnames,
                default=FALSE)
            private$..pct <- jmvcore::OptionBool$new(
                "pct",
                pct,
                default=FALSE)
            private$..mytitle <- jmvcore::OptionString$new(
                "mytitle",
                mytitle,
                default="Variable Tree")
            private$..imagewidth <- jmvcore::OptionInteger$new(
                "imagewidth",
                imagewidth,
                default=10)

            self$.addOption(private$..vars)
            self$.addOption(private$..excl)
            self$.addOption(private$..horizontal)
            self$.addOption(private$..sline)
            self$.addOption(private$..varnames)
            self$.addOption(private$..pct)
            self$.addOption(private$..mytitle)
            self$.addOption(private$..imagewidth)
        }),
    active = list(
        vars = function() private$..vars$value,
        excl = function() private$..excl$value,
        horizontal = function() private$..horizontal$value,
        sline = function() private$..sline$value,
        varnames = function() private$..varnames$value,
        pct = function() private$..pct$value,
        mytitle = function() private$..mytitle$value,
        imagewidth = function() private$..imagewidth$value),
    private = list(
        ..vars = NA,
        ..excl = NA,
        ..horizontal = NA,
        ..sline = NA,
        ..varnames = NA,
        ..pct = NA,
        ..mytitle = NA,
        ..imagewidth = NA)
)

vartreeResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        todo = function() private$.items[["todo"]],
        text1 = function() private$.items[["text1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Variable Tree",
                refs=list(
                    "vtree"))
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="To Do"))
            self$add(jmvcore::Html$new(
                options=options,
                name="text1",
                title="Variable Tree Html"))}))

vartreeBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "vartreeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'ClinicoPathDescriptives',
                name = 'vartree',
                version = c(1,0,0),
                options = options,
                results = vartreeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Variable Tree
#'
#' Function for Generating Tree Summaries of Variables.
#'
#' @examples
#' \dontrun{
#' # example will be added
#'}
#' @param data The data as a data frame.
#' @param vars .
#' @param excl .
#' @param horizontal .
#' @param sline .
#' @param varnames .
#' @param pct .
#' @param mytitle .
#' @param imagewidth .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text1} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
vartree <- function(
    data,
    vars,
    excl = TRUE,
    horizontal = FALSE,
    sline = TRUE,
    varnames = FALSE,
    pct = FALSE,
    mytitle = "Variable Tree",
    imagewidth = 10) {

    if ( ! requireNamespace('jmvcore'))
        stop('vartree requires jmvcore to be installed (restart may be required)')

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- vartreeOptions$new(
        vars = vars,
        excl = excl,
        horizontal = horizontal,
        sline = sline,
        varnames = varnames,
        pct = pct,
        mytitle = mytitle,
        imagewidth = imagewidth)

    analysis <- vartreeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
