
# This file is automatically generated, you probably don't want to edit this

vartreeOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "vartreeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            percvar = NULL,
            percvarLevel = NULL,
            excl = TRUE,
            vp = TRUE,
            horizontal = FALSE,
            sline = TRUE,
            varnames = FALSE,
            pct = FALSE,
            legend = FALSE,
            mytitle = "Variable Tree",
            width = 1000,
            height = 1000, ...) {

            super$initialize(
                package='ClinicoPathDescriptives',
                name='vartree',
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..percvar <- jmvcore::OptionVariable$new(
                "percvar",
                percvar)
            private$..percvarLevel <- jmvcore::OptionLevel$new(
                "percvarLevel",
                percvarLevel,
                variable="(percvar)")
            private$..excl <- jmvcore::OptionBool$new(
                "excl",
                excl,
                default=TRUE)
            private$..vp <- jmvcore::OptionBool$new(
                "vp",
                vp,
                default=TRUE)
            private$..horizontal <- jmvcore::OptionBool$new(
                "horizontal",
                horizontal,
                default=FALSE)
            private$..sline <- jmvcore::OptionBool$new(
                "sline",
                sline,
                default=TRUE)
            private$..varnames <- jmvcore::OptionBool$new(
                "varnames",
                varnames,
                default=FALSE)
            private$..pct <- jmvcore::OptionBool$new(
                "pct",
                pct,
                default=FALSE)
            private$..legend <- jmvcore::OptionBool$new(
                "legend",
                legend,
                default=FALSE)
            private$..mytitle <- jmvcore::OptionString$new(
                "mytitle",
                mytitle,
                default="Variable Tree")
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=1000)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=1000)

            self$.addOption(private$..vars)
            self$.addOption(private$..percvar)
            self$.addOption(private$..percvarLevel)
            self$.addOption(private$..excl)
            self$.addOption(private$..vp)
            self$.addOption(private$..horizontal)
            self$.addOption(private$..sline)
            self$.addOption(private$..varnames)
            self$.addOption(private$..pct)
            self$.addOption(private$..legend)
            self$.addOption(private$..mytitle)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
        }),
    active = list(
        vars = function() private$..vars$value,
        percvar = function() private$..percvar$value,
        percvarLevel = function() private$..percvarLevel$value,
        excl = function() private$..excl$value,
        vp = function() private$..vp$value,
        horizontal = function() private$..horizontal$value,
        sline = function() private$..sline$value,
        varnames = function() private$..varnames$value,
        pct = function() private$..pct$value,
        legend = function() private$..legend$value,
        mytitle = function() private$..mytitle$value,
        width = function() private$..width$value,
        height = function() private$..height$value),
    private = list(
        ..vars = NA,
        ..percvar = NA,
        ..percvarLevel = NA,
        ..excl = NA,
        ..vp = NA,
        ..horizontal = NA,
        ..sline = NA,
        ..varnames = NA,
        ..pct = NA,
        ..legend = NA,
        ..mytitle = NA,
        ..width = NA,
        ..height = NA)
)

vartreeResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        todo = function() private$.items[["todo"]],
        text1 = function() private$.items[["text1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Variable Tree",
                refs=list(
                    "vtree"))
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="To Do"))
            self$add(jmvcore::Html$new(
                options=options,
                name="text1",
                title="Variable Tree Html"))}))

vartreeBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "vartreeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'ClinicoPathDescriptives',
                name = 'vartree',
                version = c(1,0,0),
                options = options,
                results = vartreeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Variable Tree
#'
#' Function for Generating Tree Summaries of Variables.
#'
#' @examples
#' \dontrun{
#' # example will be added
#'}
#' @param data The data as a data frame.
#' @param vars .
#' @param percvar .
#' @param percvarLevel .
#' @param excl .
#' @param vp .
#' @param horizontal .
#' @param sline .
#' @param varnames .
#' @param pct .
#' @param legend .
#' @param mytitle .
#' @param width .
#' @param height .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text1} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
vartree <- function(
    data,
    vars,
    percvar,
    percvarLevel,
    excl = TRUE,
    vp = TRUE,
    horizontal = FALSE,
    sline = TRUE,
    varnames = FALSE,
    pct = FALSE,
    legend = FALSE,
    mytitle = "Variable Tree",
    width = 1000,
    height = 1000) {

    if ( ! requireNamespace('jmvcore'))
        stop('vartree requires jmvcore to be installed (restart may be required)')

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(percvar)) percvar <- jmvcore::resolveQuo(jmvcore::enquo(percvar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(percvar), percvar, NULL))


    options <- vartreeOptions$new(
        vars = vars,
        percvar = percvar,
        percvarLevel = percvarLevel,
        excl = excl,
        vp = vp,
        horizontal = horizontal,
        sline = sline,
        varnames = varnames,
        pct = pct,
        legend = legend,
        mytitle = mytitle,
        width = width,
        height = height)

    analysis <- vartreeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
