
# This file is automatically generated, you probably don't want to edit this

waterfallOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "waterfallOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            patientID = NULL,
            response = NULL,
            sortBy = "response",
            showThresholds = FALSE,
            labelOutliers = FALSE,
            showMedian = FALSE,
            showCI = FALSE,
            minResponseForLabel = 50,
            colorScheme = "jamovi",
            barAlpha = 1,
            barWidth = 0.7,
            addResponseCategory = FALSE, ...) {

            super$initialize(
                package="ClinicoPathDescriptives",
                name="waterfall",
                requiresData=TRUE,
                ...)

            private$..patientID <- jmvcore::OptionVariable$new(
                "patientID",
                patientID,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..response <- jmvcore::OptionVariable$new(
                "response",
                response,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sortBy <- jmvcore::OptionList$new(
                "sortBy",
                sortBy,
                options=list(
                    "response",
                    "id"),
                default="response")
            private$..showThresholds <- jmvcore::OptionBool$new(
                "showThresholds",
                showThresholds,
                default=FALSE)
            private$..labelOutliers <- jmvcore::OptionBool$new(
                "labelOutliers",
                labelOutliers,
                default=FALSE)
            private$..showMedian <- jmvcore::OptionBool$new(
                "showMedian",
                showMedian,
                default=FALSE)
            private$..showCI <- jmvcore::OptionBool$new(
                "showCI",
                showCI,
                default=FALSE)
            private$..minResponseForLabel <- jmvcore::OptionNumber$new(
                "minResponseForLabel",
                minResponseForLabel,
                default=50,
                min=0,
                max=100)
            private$..colorScheme <- jmvcore::OptionList$new(
                "colorScheme",
                colorScheme,
                options=list(
                    "jamovi",
                    "recist",
                    "simple"),
                default="jamovi")
            private$..barAlpha <- jmvcore::OptionNumber$new(
                "barAlpha",
                barAlpha,
                default=1,
                min=0,
                max=1)
            private$..barWidth <- jmvcore::OptionNumber$new(
                "barWidth",
                barWidth,
                default=0.7,
                min=0.1,
                max=1)
            private$..addResponseCategory <- jmvcore::OptionBool$new(
                "addResponseCategory",
                addResponseCategory,
                default=FALSE)

            self$.addOption(private$..patientID)
            self$.addOption(private$..response)
            self$.addOption(private$..sortBy)
            self$.addOption(private$..showThresholds)
            self$.addOption(private$..labelOutliers)
            self$.addOption(private$..showMedian)
            self$.addOption(private$..showCI)
            self$.addOption(private$..minResponseForLabel)
            self$.addOption(private$..colorScheme)
            self$.addOption(private$..barAlpha)
            self$.addOption(private$..barWidth)
            self$.addOption(private$..addResponseCategory)
        }),
    active = list(
        patientID = function() private$..patientID$value,
        response = function() private$..response$value,
        sortBy = function() private$..sortBy$value,
        showThresholds = function() private$..showThresholds$value,
        labelOutliers = function() private$..labelOutliers$value,
        showMedian = function() private$..showMedian$value,
        showCI = function() private$..showCI$value,
        minResponseForLabel = function() private$..minResponseForLabel$value,
        colorScheme = function() private$..colorScheme$value,
        barAlpha = function() private$..barAlpha$value,
        barWidth = function() private$..barWidth$value,
        addResponseCategory = function() private$..addResponseCategory$value),
    private = list(
        ..patientID = NA,
        ..response = NA,
        ..sortBy = NA,
        ..showThresholds = NA,
        ..labelOutliers = NA,
        ..showMedian = NA,
        ..showCI = NA,
        ..minResponseForLabel = NA,
        ..colorScheme = NA,
        ..barAlpha = NA,
        ..barWidth = NA,
        ..addResponseCategory = NA)
)

waterfallResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "waterfallResults",
    inherit = jmvcore::Group,
    active = list(
        todo = function() private$.items[["todo"]],
        summary = function() private$.items[["summary"]],
        mydataview = function() private$.items[["mydataview"]],
        clinicalMetrics = function() private$.items[["clinicalMetrics"]],
        plot = function() private$.items[["plot"]],
        responseCategory = function() private$.items[["responseCategory"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Treatment Response Waterfall Plot",
                refs=list(
                    "recist",
                    "ClinicoPathJamoviModule"))
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="To Do"))
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Response Summary",
                rows=0,
                columns=list(
                    list(
                        `name`="category", 
                        `title`="Response Category", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="n", 
                        `type`="integer"),
                    list(
                        `name`="percent", 
                        `title`="%", 
                        `type`="number", 
                        `format`="percent"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="mydataview",
                title="mydataview"))
            self$add(jmvcore::Table$new(
                options=options,
                name="clinicalMetrics",
                title="Clinical Response Metrics",
                rows=0,
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Waterfall Plot",
                width=800,
                height=500,
                renderFun=".plot",
                requiresData=TRUE,
                clearWith=list(
                    "patientID",
                    "response",
                    "sortBy",
                    "showThresholds",
                    "labelOutliers",
                    "colorScheme",
                    "showMedian",
                    "showCI")))
            self$add(jmvcore::Output$new(
                options=options,
                name="responseCategory",
                title="Response Category",
                varTitle="`Calculated Response Category`",
                varDescription="Calculated response category based on RECIST criteria.",
                clearWith=list(
                    "patientID",
                    "response")))}))

waterfallBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "waterfallBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ClinicoPathDescriptives",
                name = "waterfall",
                version = c(1,0,0),
                options = options,
                results = waterfallResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Treatment Response Waterfall Plot
#'
#' Creates a waterfall plot to visualize tumor response data following RECIST 
#' criteria.
#'
#' @examples
#' \donttest{
#' data <- data.frame(
#'     PatientID = paste0("PT", 1:10),
#'     Response = c(-100, -45, -30, -20, -10, 0, 10, 20, 30, 40)
#' )
#' waterfall(
#'     data = data,
#'     patientID = "PatientID",
#'     response = "Response"
#' )
#'}
#' @param data The data as a data frame.
#' @param patientID Variable containing patient identifiers.
#' @param response Percentage change in tumor size.
#' @param sortBy .
#' @param showThresholds Show +20 percent and -30 percent RECIST thresholds.
#' @param labelOutliers Label responses exceeding ±50 percent.
#' @param showMedian .
#' @param showCI .
#' @param minResponseForLabel .
#' @param colorScheme .
#' @param barAlpha .
#' @param barWidth .
#' @param addResponseCategory .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mydataview} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$clinicalMetrics} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$responseCategory} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
waterfall <- function(
    data,
    patientID,
    response,
    sortBy = "response",
    showThresholds = FALSE,
    labelOutliers = FALSE,
    showMedian = FALSE,
    showCI = FALSE,
    minResponseForLabel = 50,
    colorScheme = "jamovi",
    barAlpha = 1,
    barWidth = 0.7,
    addResponseCategory = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("waterfall requires jmvcore to be installed (restart may be required)")

    if ( ! missing(patientID)) patientID <- jmvcore::resolveQuo(jmvcore::enquo(patientID))
    if ( ! missing(response)) response <- jmvcore::resolveQuo(jmvcore::enquo(response))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(patientID), patientID, NULL),
            `if`( ! missing(response), response, NULL))


    options <- waterfallOptions$new(
        patientID = patientID,
        response = response,
        sortBy = sortBy,
        showThresholds = showThresholds,
        labelOutliers = labelOutliers,
        showMedian = showMedian,
        showCI = showCI,
        minResponseForLabel = minResponseForLabel,
        colorScheme = colorScheme,
        barAlpha = barAlpha,
        barWidth = barWidth,
        addResponseCategory = addResponseCategory)

    analysis <- waterfallClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

