# GENERATED by _updateModules tooling: @importFrom tags to satisfy R CMD check
# 'Namespaces in Imports field not imported from' NOTE for pkg::-used packages.
#' @importFrom boot boot
#' @importFrom classInt classIntervals
#' @importFrom DescTools BreslowDayTest
#' @importFrom finalfit summary_factorlist
#' @importFrom ggcharts pyramid_chart
#' @importFrom MASS ginv
#' @importFrom pwr pwr.chisq.test
#' @importFrom RColorBrewer brewer.pal.info
#' @importFrom scales percent
#' @importFrom tangram html5
#' @importFrom viridis viridis
#' @importFrom grDevices adjustcolor col2rgb colorRampPalette
#' @importFrom naniar mcar_test
#' @importFrom stringr str_to_sentence str_to_title
#' @importFrom visdat vis_dat vis_guess vis_miss
NULL

